wa72_json_rpc:
    path: /
    defaults: { _controller: 'Wa72\JsonRpcBundle\Controller\JsonRpcController::execute', optionalTrailingSlash : "/" }
    requirements: { optionalTrailingSlash : "[/]{0,1}" }
